name: Manual Trigger Workflow

on:
    workflow_dispatch: # manual trigger

jobs:
    say-hello: # job name
        runs-on: ubuntu-latest # runner
        steps: # steps
            - name: Checkout code # step name
              uses: actions/checkout@v4

            - name: Say Hello # step name
              run: |
                echo "Hello World Workflow! - manual trigger"
                echo "Repository: ${{ github.repository }}"
                echo "Ref: ${{ github.ref }}"
                echo "Actor: ${{ github.actor }}"
                echo "Event Name: ${{ github.event_name }}"
                echo "Branch: ${{ github.ref_name }}"
                echo "Workflow: ${{ github.workflow }}"